name: Python Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m venv venv
        venv\Scripts\pip install -r requirement.txt

    - name: Run tests and generate JUnit report
      run: |
        mkdir results
        venv\Scripts\pytest tests --junitxml=results\TEST-results.xml

    - name: Upload test report
      uses: actions/upload-artifact@v4
      with:
        name: junit-test-results
        path: results/TEST-results.xml

    - name: Run Tests with Allure
      run: | 
        venv\Scripts\activate
        mkdir allure-results
        pytest tests --alluredir=allure-results

    - name: Upload Allure Results as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: allure-results
        path: allure-results

    - name: Install Allure CLI
      run: |
        choco install allure.commandline -y
        set PATH=%PATH%;"C:\ProgramData\chocolatey\lib\allure.commandline\tools\allure-2.24.0\bin"

    - name: Generate Allure Report
      run: allure generate allure-results -o allure-report --clean
  
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report
